### ISSUE TITLE
Flow is run and failed on buffer without file

### ISSUE THREAD

**Issue by ul** [an-sh/flow-minor-mode#15]
When I work in buffer without corresponding file (just created and not saved yet), I get the following error in other buffer:

```
Could not find file or directory <path-to-my-file>/story.js; canceling search for .flowconfig.
See "flow init --help" for more info

Process flow-minor-eldoc stderr finished
```

The most annoying part of it is that it steals focus from current buffer, and do that on any edit until I save buffer.

Would you mind looking into it? How should this be mitigated?

Thank you!

**Comment by xiazhe** [comment]
same issue, "flow-bin": "^0.182.0"

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> vue3-flow@0.0.0 flow
> flow check "init"

Could not find file or directory init; canceling search for .flowconfig.
See "flow init --help" for more info
