### ISSUE TITLE
Please fixup the LICENSE file

### ISSUE THREAD

**Issue by tarsius** [an-sh/flow-minor-mode#18]
For the [Emacsmirror](https://emacsmirror.net) I need to determine the license of all mirrored packages. When there is license information in the "main" library, then that is used. Otherwise my tools fall back to use [`licensee`](https://github.com/benbalter/licensee), which extracts the information from the `LICENSE` file and similar. Unfortunately in this case it fails.

I think that's because you
* begin with a line `BSD License` but `licensee` expects that line to be `BSD 3-Clause License` or be missing
* added the unexpected line `For flow-for-emacs software`,
* use a copyright year range `2016-present`,
* don't put `All rights reserved.` on a separate line, and
* generally wrap lines differently (though that *probably* doesn't make a difference).

Please change that to help tools that try to extract the license. Thanks!

You might want to use https://github.com/benbalter/licensee/blob/master/vendor/choosealicense.com/_licenses/bsd-3-clause.txt#L30-L56 as a template.

Also, is `Copyright (c) 2016-present, Facebook, Inc.` correct?

**Comment by an-sh** [comment]
It is just a copy-paste of the original licence from the mode made by facebook, the code itself was largely rewritten (i'm not sure if there is any original code left actually). I think i can reformat the file since it doesn't change any legal meaning.

**Comment by an-sh** [comment]
Well, actually the 3rd clause is also different here, so it doesn't fit the proposed template, so i think i have to leave it as it is.

**Comment by tarsius** [comment]
The only difference is `s/Facebook/of the copyright holder/`, and given the copyright line these two things are equivalent. Also I think that even if you kept `Facebook` (but made the other changes), then `licensee` should still be able to detect the license.

**Comment by an-sh** [comment]
I've updated the formatting, hope it will help.

**Comment by tarsius** [comment]
Thanks!
