### ISSUE TITLE
Should this be a minor mode?

### ISSUE THREAD

**Issue by aaronjensen** [an-sh/flow-minor-mode#2]
Not everyone uses web-mode with flow. Furthermore, not everyone uses `.flow.js` suffixes or even the `// @flow` marker. It's hard to tell what files are flow files and modes like `rjsx-mode` are still reasonable major modes for flow.

What you have in this package is super useful and great, but I think it should be a minor mode so that it can be overlaid on top of web-mode or rjsx-mode and we can more easily set up our hooks to look for `.flowconfig` or whatever logic we want.

Thanks for putting this together and releasing it!

**Comment by an-sh** [comment]
As far as i understand both js2-mode and rjsx-mode (which is derived from js2-mode) are using JavaScript (or jsx) parser to build an AST, so they can't correctly parse flow files. Right now web-mode seems the most advantageous solution (as flow can be used inside jsx files too). 

There is a problem to identify flow files, the best solution i can think of is to provide a hook that can be used in other major modes for automatically switching to flow-mode if `// @flow `marker is detected. Refactoring in minor mode probably not worth it, because flow syntax is actually different from the standard JavaScript. But i'm still not 100% sure about it.

**Comment by aaronjensen** [comment]
You're right that they're based on js2-mode which cannot parse flow files correctly. In practice this makes little difference unless you want to use any of the js2-mode refactoring tools (which don't work). Indentation and syntax highlighting work well enough. At this point I can't even remember why I switched from web-mode to rjsx-mode. There are things like [this](https://github.com/fxbois/web-mode/issues/810) that are annoying in web-mode.

That said, I'm not 100% sure either about flow-mode being a minor or major mode. I think that if flow-mode added additional syntax highlighting, indentation rules, etc then it'd be great as a major mode, similar to typescript-mode. Given that it's just adding some keybindings at the moment and that different people have different preferences on major modes it feels more like a minor mode. Theoretically you could even define two major modes, one based on rjsx-mode and the other on web-mode, but that'd probably be a maintenance headache.

**Comment by asf-stripe** [comment]
I too would love if this was a minor mode. If you don't object, I'll try and take a stab at reworking this mode this weekend (:

**Comment by antifuchs** [comment]
I too would love if this was a minor mode. Unless anyone objects, I'll try and work these bits into one (and submit a pull req) this weekend.

**Comment by an-sh** [comment]
If someone is interested in minor mode overlaid on something other than web-mode, then i don't actually see anything against it (i don't have any plans to add syntax highlighting or indenting in the near feature). PR are welcomed.

**Comment by an-sh** [comment]
@antifuchs thanks for the PRs. If there are no regressions (bug reports / PRs are welcomed) i'll try to republish (rename) package in melpa as flow-minor-mode with 0.2 version somewhere on the next week.

**Comment by aaronjensen** [comment]
@antifuchs awesome work, thanks! 

I tested this briefly and it seems to work quite well. Once this is released, I can update company-flow to check for the minor mode instead of a list of major modes the user can specify. Do you think that seems reasonable? Or should I maintain support for [`company-flow-modes`](https://github.com/aaronjensen/company-flow#configuration)?

**Comment by aaronjensen** [comment]
Oh, one other thing @antifuchs, do you think you should check for a dominating `.flowconfig` in `flow-enable-automatically`? Nothing will work w/o it.

**Comment by antifuchs** [comment]
I added that check - thanks for the suggestion!

I think activating company-flow only in flow-minor mode would probably make all sorts of config much easier for users (you could piggyback `company-flow-executable` off of this mode?), so I'm quite in favor (:

**Comment by aaronjensen** [comment]
I believe this has been addressed 😄  thanks @antifuchs.
